# Ignore app, bin, tests and vendor folders
filter:
    excluded_paths:
        - 'app/*'
        - 'bin/*'
        - 'tests/*'
        - 'vendor/*'

checks:
    php: true

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: false
            other:
                after_type_cast: false

# Travis-CI send phpunit's tests reports
tools:
    external_code_coverage:
        timeout: 1200
        runs: 1
