# See http://about.travis-ci.org/docs/user/languages/php/ for more hints.
language: php

# PHP versions we want to test.
php:
    - 5.6
    - 7.0
    - nightly
    - hhvm

# We allow failures for HHVM only.
matrix:
    allow_failures:
        - php:
            - nightly
            - hhvm

# Mandatory scripts before the app is ready to be tested.
before_script:
    - echo $TRAVIS_PHP_VERSION
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - sed -i "s/database_user:.*/database_user:\ travis/" app/config/parameters.yml
    - sed -i "s/database_password:.*/database_password:\ null/" app/config/parameters.yml
    - npm install
    - npm install -g bower brunch
    - bower install --config.interactive=false
    - brunch build --production
    - composer self-update
    - composer install --prefer-source --optimize-autoloader --no-interaction
    - bin/console doctrine:database:create --no-interaction
    - bin/console doctrine:schema:create --no-interaction
    - bin/console cache:warmup --env=test --no-debug

# Run PHPUnit and generate code coverage report in Clover XML format.
script:
    - if [[ $TRAVIS_PHP_VERSION = "7.0" ]] ; then phpunit --coverage-clover=coverage.clover ; else phpunit ; fi

# Send generated report to Scrutinizer
after_script:
    - if [[ $TRAVIS_PHP_VERSION = "7.0" ]] ; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover ; fi
