security:

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 30

    providers:
        db_provider:
            entity:
                class: AppBundle:User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: ~
            provider: db_provider
            switch_user:
                role: ROLE_ALLOWED_TO_SWITCH
            form_login:
                login_path: /login
                check_path: /login_check
                use_referer: true
                csrf_provider: security.csrf.token_manager
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
